
main:
  - identifier: posts
    name: Posts
    url: en/posts
    weight: 1
  - identifier: categories
    name: Categories
    url: en/categories
    weight: 10
  - identifier: tags
    name: Tags
    url: en/tags
    weight: 20
  - identifier: contact
    name: Contact
    url: en/contact
    weight: 30
  - identifier: about
    name: About
    url: en/about
    weight: 35
  - identifier: github
    name: GitHub
    url: https://github.com/jcnm/blog
    weight: 40